### ISSUE TITLE
Chance #! line in manage.py to use env

### ISSUE THREAD

**Issue by godber** [tobami/overmind#3]
For users who use virtualenv or otherwise manage their system pythons, it is inconvenient to have the python interpreter hard coded into the manage.py.  Please consider changing the #! line in manage.py:

https://github.com/tobami/overmind/blob/master/overmind/manage.py#L1

from
    #!/usr/bin/python
to 
    #!/usr/bin/env python

Ausitn

**Comment by tobami** [comment]
Done.
Commit a7ce2c3372ca2b6ea8f1bda5223b59b0fc54020e  fixes this issue.
